{
 "title": "Jetstream",
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Amount of stations in time range",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 },
   "targets": [
    {
     "dataset": "jetstream",
     "rawSql": "SELECT count(distinct station_id) as count,\n(select count(station_id) from jetstream.stations) as max_count\nFROM jetstream.wind_data\nwhere measurement_date between $__timeFrom() and $__timeTo()"
    }
   ]
  },
  {
   "title": "Amount of datasets in time range",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 0 },
   "targets": [
    {
     "dataset": "jetstream",
     "rawSql": "SELECT COUNT(*) as count_all FROM jetstream.wind_data"
    },
    {
     "dataset": "jetstream",
     "rawSql": "SELECT COUNT(*) count_filtered FROM jetstream.wind_data where measurement_date between $__timeFrom() and $__timeTo() "
    }
   ]
  },
  {
   "title": "Amount of entries over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 0 },
   "targets": [
    {
     "dataset": "jetstream",
     "rawSql": "SELECT measurement_date as \"time\", \r\n    COUNT(*) as \"value\" \r\nFROM jetstream.wind_data \r\nGroup by measurement_date"
    }
   ]
  },
  {
   "title": "Last wind speed per station",
   "type": "geomap",
   "description": "moderate wind speed >= 5  \nhigh wind speed >= 10  \nextreme wind speed >= 17  \n(see https://www.wetterkontor.de/de/bft_tabelle.html)",
   "gridPos": { "h": 16, "w": 10, "x": 0, "y": 5 },
   "targets": [
    {
     "dataset": "jetstream",
     "rawSql": "SELECT\r\n    s.station_id AS ID,\r\n    s.name AS name,\r\n    s.longitude,\r\n    s.latitude,\r\n    wd.wind_speed,\r\n    wd.wind_direction as wind_direction_from,\r\n    (wd.wind_direction + 180) mod 360 as wind_direction_to,\r\n    wd.measurement_date\r\nFROM\r\n    jetstream.stations AS s\r\nleft JOIN\r\n    jetstream.wind_data AS wd ON s.station_id = wd.station_id\r\nWHERE\r\n    wd.measurement_date is null or wd.measurement_date = (\r\n        SELECT MAX(wd2.measurement_date)\r\n        FROM jetstream.wind_data AS wd2\r\n        WHERE wd2.station_id = wd.station_id\r\n    )"
    }
   ]
  },
  {
   "title": "Average wind speed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 7 },
   "targets": [
    {
     "dataset": "jetstream",
     "rawSql": "SELECT AVG(wind_speed) AS \"value\", measurement_date AS \"time\" FROM jetstream.wind_data GROUP BY measurement_date "
    }
   ]
  },
  {
   "title": "All stations today with high wind speed as last data point",
   "type": "table",
   "description": "high wind speed >= 10 m/s\nextreme wind speed >=17 m/s  \n(see https://www.wetterkontor.de/de/bft_tabelle.html)",
   "gridPos": { "h": 7, "w": 14, "x": 10, "y": 14 },
   "targets": [
    {
     "dataset": "jetstream",
     "rawSql": "SELECT s.station_id,\r\n      name,\r\n      state,\r\n      wind_speed,\r\n      wind_direction,\r\n      measurement_date\r\nFROM jetstream.wind_data as wd\r\nJoin jetstream.stations as s on wd.station_id = s.station_id\r\nwhere wind_speed >= 10 and date(measurement_date) = curdate()\r\nand wd.measurement_date = (\r\n        SELECT MAX(wd2.measurement_date)\r\n        FROM jetstream.wind_data AS wd2\r\n        WHERE wd2.station_id = wd.station_id\r\n    )"
    }
   ]
  }
 ]
}